---
title: "AVNER KANTOR | CURRICULUM VITAE"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'index.html'))})
output:
  word_document: default
  html_document:
    df_print: paged
---
[< home](index.html)

May 25, 2021

CONTACT INFORMATION
: Phone: +972-54-7820-256
: E-mail: avnerkantor@gmail.com
: Website: [avnerkantor.com](http://avnerkantor.com)

<!-- 
RESEARCH INTERESTS
: Data journalism, Citizen empowerment 
-->


| EDUCATION    | 
| --------- |------------------------------------------------------------------ |
| 2023 | Ph.D. Candidate, School of business administration, University of Haifa.<br/>  Advisor: [Prof. Sheizaf Rafaeli](https://sites.google.com/rafaeli.net/sheizaf).<br/>Thesis Topic: *Effects of Transparency on Public Trust in Data Journlaism* |
| 2019 | Master’s research and thesis, Information & Knowledge Management, University of Haifa.<br/>  Advisor: Prof. Sheizaf Rafaeli.<br/>Thesis Topic: *Data Journalism, Transparency and Interactivity* |
| 2015 | MA, Philosophy Education, Hebrew University of Jerusalem |
| 2010 | Teacher Certification program, Hebrew University of Jerusalem|
| 2010 | B.A., Philosophy and Interdisciplinary program, Hebrew University of Jerusalem|
<!-- 1994-1997| Israel Arts and Science Academy|-->


| ARTICLES    | 
| --------- |------------------------------------------------------------------ |
|2020 |Kantor, Avner, and Sheizaf Rafaeli. ["Open PISA: Dashboard for Large Educational Dataset."](https://dl.acm.org/doi/abs/10.1145/3386527.3406721) In Proceedings of the Seventh ACM Conference on Learning@ Scale, pp. 253-256. 2020. |
|2013 |Kantor, Avner. [“Dream and Hope”](https://books.google.co.il/books?id=MhpLAgAAQBAJ&pg=PA33). *Narrative, Dreams, Imagination* 3 (2013): 33. |


| CONFERENCES   | 
| --------- |------------------------------------------------------------------ |
| 2021 | "Does Data Journalism Engage Its Audience?", Computation + Journalism Symposium, Virtual Event, USA, March 20 – 21, 2020
| 2020 | ["Open PISA: Dashboard for Large Educational Dataset"](https://www.youtube.com/watch?v=1ZcaSSY-5ag), Learning at Scale, Virtual Event, USA, August 12–14, 2020 | 
| 2017 | ["Big Data and Citizen Empowerment"](https://www.youtube.com/watch?v=U_-jka7O8H4), Public Policy and Politics in The Age of Media and Data, Open University of Israel, Ra'anana, December 24, 2017 | 
| | "Transparency and Interactivity: Does Data Journalism Effects Civic Engagement", Rabin Graduate Conference on Political Science, International Relations, and Public Policy, Hebrew University of Jerusalem, Jerusalem, December 13-14, 2017
| | ["Education Data Journalism"](https://www.youtube.com/watch?v=1ZcaSSY-5ag), The Israeli Visualization Conference (ISVIS), Haifa University, Haifa, June 27, 2017 | 
| |"How can the public be encouraged to investigate educational questions? The PISA Citizen Science Project", Public Engagement with Science Online – A Research Workshop of the Israel Science Foundation, Technion, Haifa, June 25t, 2017|
| | "Big Data and Education: PISA Test",  INFO Annual Conference & Exhibition - Teldan Information Systems, Tel-Aviv, May 11, 2017|
| 2015 | "PISA Data Explorer", Learning in a Networked Society (LINKS) Annual Retreat, Ben Gurion University, Beer-Sheva, September 8-9, 2015|
| 2014 | "Education Data Transparency", Learning in a Networked Society (LINKS) Annual Retreat, Haifa University, September 18, 2014|
| 2009 | "Philosophy for Children and Bilingual Education", IPCRI Education for Peace Conference & Workshops, Tantur, Jerusalem, Apr 24-25, 2009|
| 2007 | "Meaning of Life and Education", International Council of Philosophical Inquiry with Children, Hebrew University of Jerusalem, Jerusalem, June 4-7, 2007|

| SEMINARS   |
| --------- |------------------------------------------------------------------ |
| 2017 | "Data Journalism and Education", Faculty of Education Science and Technology, Technion, November 14, 2017|
|  | "Education Data Journalism",  [Open Media and Information Lab](http://www.openu.ac.il/en/omilab/pages/default.aspx), Open University of Israel, Ra'anana, February 22, 2017|
| | "Open PISA Project", Education Seminar, Israel Central Bureau of Statistics, Jerusalem, February 22, 2017 |
| 2016 | "Open PISA Project", National Authority for Measurement and Evaluation in Education, Ramat-Gan, December 28, 2016| 
| | "Visualization of Education", Education Seminar, Israel Central Bureau of Statistics, Jerusalem, Januar 21, 2016|
| 2015 | "Data Journalism", Special Seminar for World Statistics Day, Israel Central Bureau of Statistics, Jerusalem, October 22, 2015|

| SERVICE | 
| --------- |------------------------------------------------------------------ |
| 2010 | Workshop: Imaging the Future, Hebrew University of Jerusalem, Jerusalem, 2010 |
| 2009 | Workshop: Education for Thinking: Inquiry, Creativity and Philosophy, Israel Center for Excellence through Education, Jerusalem, December 13, 2009
| 2007 | Conference: International Council of Philosophical Inquiry with Children, Hebrew University of Jerusalem, Jerusalem, June 4-7, 2007|



| TEACHING   |
| --------- |------------------------------------------------------------------ |
| Spring 2021 | "Introduction to Data Science for Government", [Lauder School of Government, Diplomacy & Strategy](https://www.idc.ac.il/en/schools/government/pages/home.aspx) IDC  Herzliya|


| GRANTS    | 
| --------- |----------------------------------------------------------| -------- |
| 2018 | Samuel Neaman Institute for [Israel 100: Wikipedia digital footprint](https://avnerkantor.shinyapps.io/israel100/) (in collaboration with Prof. Sheizaf Rafaeli)| 20,000 NIS |
| 2017-2019 | [AllCloud](https://allcloud.io/) for hosting [Open PISA Project](http://openpisa.org/) | 11,000$ |
| 2015-2020 | [The Trump Foundation](https://trump.org.il/en/) for developing [Open PISA Project](http://openpisa.org/) (in collaboration with Prof. Sheizaf Rafaeli)| 400,000 NIS |
| 2010-2011 | DAAD Center for German Studies in the Hebrew University of Jerusalem for Israeli-German research project (in collaboration with Dr. Jen Glasser)| 10,000$ |
| 2007 | The Melton Center for Jewish Education in the Hebrew University of Jerusalem for international ICPIC conference (in collaboration with Dr. Jen Glasser)| 10,000$ |
| 2006 | The School of Education in the Hebrew University of Jerusalem for Philosophy in Primary Schools Project (in collaboration with Dr. Jen Glasser)| 10,000 NIS |
| | The Jerusalem Foundation for Philosophy in Primary Schools Project (in collaboration with Dr. Jen Glasser) | 5,000$|


| INDUSTRY  | 
| --------- |------------------------------------------------------------------ |
| 2020- 2021| Corona National Information and Knowledge Center, Data Scientist|
| 2018-2020 | [The Center for Educational Technology](https://home.cet.ac.il/?lang=en), Data Scientist|
| 2015-2017 | [The Center for Internet Research](https://internetcenter.haifa.ac.il/index.php/en/home-english/48-about), Research Fellow|
| 2012-2013 | [Elenxos](https://finder.startupnationcentral.org/company_page/elenxos), Software Developer|
| 2008-2011 | Ministry of Education, Science and Math Teacher|
| 2004-2008 | [Jerusalem Science Museum](http://www.mada.org.il/en), Instructor|
<!--|1997-2001 | Israel Defense Forces, Science Technology Intelligence Analyst |-->

**REFEREE SERVICE**
: Hawaii International Conference on System Sciences (HICSS), ACM CHI Conference on Human Factors in Computing Systems, Public Understanding of Science (PUS)


<br/>**Volunteering** 
: Wikipedia, Wikimedia, Open Knowledge Workshop, Association of Engineers in Israel, Israel R User Group.


<br/>**REFERENCE**
: Prof. Sheizaf Rafaeli (Ph.D. advisor)
: President of [Shenkar College of Engineering and Design](https://www.shenkar.ac.il/en) 
: Email: sheizaf@rafaeli.net 
